# Introduction to Computer Vision for Robotics

In this tutorial you will be introduced to some basic concepts of computer vision and programming and have the chance to practice yourself.

### Jupyter Notebooks

As you've found out by now, this tutorial is run using a jupyter notebook. This is an online programming environment which has been set up to take you through the tasks for this tutorial. Things to note with jupyter notebooks:
 - There are two types of 'cells', text cells like this one and code cells shown by the [?]: symbol at the side which contain the code that you'll run. As you go through feeel free to edit code cells and see what happens when you change them.
 - To run a cell press shift-enter or click the run button at the top of the page.
 - Sometimes you can accidentally enter editing mode of the text cells, if that happens just run the cell (shift-enter) to exit editing mode.
 - Some cells refer to variables created in other cells so make sure to run all cells in order
 
This notebook is set up to run with the Python programming language. Different languages are structured and written differently which makes them good for different tasks, Python is a powerful language that's used a lot in research and is also relatively easy to start using.

### Tutorial Structure

This tutorial will give you a quick introduction to some core programming concepts and also some computer vision tasks. The first part will give and introduction to basic programming concepts, if you've done some programming before feel free to go over these quickly. The sections to this tutorial are:
 - Basic Programming Concepts
 - What are digital images?
 - Filtering an image
 - Edge detection



## Basic Programming Concepts

When programming, a piece of data has a a name and a data type. In this tutorial we'll use four data types:
 - int - Used for storing an integer, i.e. a whole number
 - float - Used for storing a floatimg point number, i.e. with decimal point
 - str - Used for storing a String, i.e. sequence of characters
 - list - Stores a comma separated list of data
 - array - Stores an array of data, we'll be using a library called 'numpy' which is useful for performing operations arrays. A library is some code written to perform specific operations, in this case the numpy library has useful inbuilt operation for dealing with large data arrays.
 
In code you'll see two types of text, the actual code and comments. Comments are used to explain what's goin on in the code but aren't run by the program, in Python a comment is made by starting with the # symbol and are shown as italicised text. If you're not sure what some part of the code is doing try reading the comments for an explanation.

The print statement is used to display a variable or message to the user. The structure is print( *variable name* ) or print( "*message*" ).

The type() function isused to retrieve the type of a variable, e.g. type(*variable*)

Try running the code cell below and make sure you understand where all the oupt statements are coming from.

In [21]:
import numpy as np # Import the numpy library, name it np

print("Hello, World!") # print a message

a = int() # Create blank int variable
print(a) # print variable a
print(type(a)) # print type of variable a

a = 9 # Set value of a to 9
b = 9.3 # Create a float
c = a + b # basic arithmitic
d = "Hello, World!" # Create a string
e = ["A list", 6, 9.4, ["A list", "In a list"]] # A list
f = np.array((4, 5)) # Create an array with 4 rows and 5 columns
g = np.array([[1, 2, 3],[4, 5, 6]]) # Create an array with 
h = np.zeros((2, 3)) # Create an array with 
i = np.ones((1, 6)) # Create an array with 

print(a, type(a)) # We can print more than one thing in a single line by separating the variables with a comma
print(b, type(b))
print(c, type(c))
print(d, type(d))
print(e, type(e))
print(f, type(f), f.shape)
print(g, type(g))
print(h, type(h))
print(i, type(i))

Hello, World!
0
<class 'int'>
9 <class 'int'>
9.3 <class 'float'>
18.3 <class 'float'>
Hello, World! <class 'str'>
['A list', 6, 9.4, ['A list', 'In a list']] <class 'list'>
[4 5] <class 'numpy.ndarray'> (2,)
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>
[[1. 1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>


### Code Structure: if, for, while

Code can be thought of as a flowchart with one instruction being executed at a time. In order to make decision we commonly use 'if' statements and to repeat sections of code we use 'while' loops or 'for' loops.

If statements are used with conditional operators to decide of a block of code should be executed. The operators must always be either true or false:
 - Equals: a == b
 - Not Equals: a != b
 - Less than: a < b
 - Less than or equal to: a <= b
 - Greater than: a > b
 - Greater than or equal to: a >= b

If statements can also have 'elif' statements (short for else if) to execute code if the first if statement is false. 'else' statements are used to execute code if none of the previous if or elif statements have been executed.

Run the example below and make sure you're happy with where the ouputs are coming from and why.

In [22]:
a = 5
b = 9

if a == 5:
    print("a equals five")

if a >= 5:
    print("a is greater than or equal to 5")
    
if a < 5:
    print("a is less than 5")
elif b >= a:
    print("b is greater than or equal to a")

if b < a:
    print("b is less than a")
elif b == a:
    print("b equals a")
else:
    print("b is greater than a")

a equals five
a is greater than or equal to 5
b is greater than or equal to a
b is greater than a


Loops are used to repeat sections of code, as we'll see they're important for image processing. 

'For' loops repeat the section of code a set number of times. This is often used with the 'range' function to define the range of values to iterate over, note range(0, 5) iterates over the values 0 to 4 not 0 to 5. For loops can also be used to iterate over the items in a list.

'while' loops are used to repeat a section of code until a condition is met. The conditional statements that can be used are the same as for the 'if' statement.

In [23]:
for a in range(0, 10):
    print(a)
    
B = ["Hello", "World", 2, 6.8, ["Another", "List"]]
for b in B:
    print(b)
    
b = 0
while b < 10:
    print(b)
    b = b + 1

0
1
2
3
4
5
6
7
8
9
Hello
World
2
6.8
['Another', 'List']
0
1
2
3
4
5
6
7
8
9
